[workspace]
members = [
    "famine-desktop",
    "famine-web",
]

[package]
name = "famine_application"
version = "0.1.0"
edition = "2021"

[lib]
name = "famine_application"
path = "./src/app.rs"
crate-type = ["rlib"]

[dependencies]
famine = { path = "famine" }